from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("",pagina_inicial,name="paginainicial"),
    path("aluno/",criaa.as_view(),name="criar_aluno"),
    path("professor/",criap.as_view(),name="criar_professor"),
    path("sobreaescola/",sobre,name="sobreescola"),
    path("imagensdaescola/",imaging,name="imagens"),
    path("directoria/",criad.as_view(),name="cria_directoria"),
    path("a/",loga,name="entra_aluno"),
    path("p/",logp,name="entra_professor"),
    path("d/",logd,name="entra_directoria"),
    path("d/<str:pk>/",dt,name="directoria_dentro"),
    path("a/<str:pk>/",al,name="aluno_dentro"),
    path("p/<str:pk>/",pr,name="professor_dentro"),
    path("entrar/",entrar,name="Entrar"),
    path("comunicados/",commm,name="todos_comunicados"),
    path("a/<str:pk>/myinfo/",upaluno,name="infoalter"),
    path("p/<str:pk>/myinfo/",upprof,name="infoalter"),
    path("d/<str:pk>/myinfo/",updir,name="infoalter"),
    path("a/<str:pk>/messgem/",mesal,name="infoalter"),
    path("p/<str:pk>/messgem/",mespr,name="infoalter"),
    path("d/<str:pk>/messgem/",mesdr,name="infoalter"),
    path("a/<str:pk>/smsenviadaparaddelength<int:l>/",mesalsee,name="infoalter"),
    path("p/<str:pk>/smsenviadaparaddelength<int:l>/",mesprsee,name="infoalter"),
    path("d/<str:pk>/smsenviadaparaddelength<int:l>/",mesdrsee,name="infoalter"),
    path("a/<str:pk>/comunicados/",comal,name="com_aluno"),
    path("p/<str:pk>/comunicados/",compr,name="com_professor"),
    path("d/<str:pk>/comunicados/",comdr,name="com_directoria"),
    path("a/<str:pk>/trabalhos/",tral,name="trabalho_aluno"),
    path("p/<str:pk>/trabalhos/",trpr,name="trabalho_professor"),
    path("d/<str:pk>/trabalhos/",trdr,name="trabalho_directoria"),
    path("a/<str:pk>/comunicados/commfgjk<str:l>",seem,name="com_al"),
    path("d/<str:pk>/comunicados/commfgjk<str:l>",seemd,name="com_dir"),
    path("p/<str:pk>/comunicados/commfgjk<str:l>",seemp,name="com_pr"),
    path("a/<str:pk>/trabalhos/commfgjk<str:l>",trma,name="com_al"),
    path("d/<str:pk>/trabalhos/commfgjk<str:l>",trmd,name="com_dir"),
    path("p/<str:pk>/trabalhos/commfgjk<str:l>",trmp,name="com_pr"),
    path("a/<str:pk>/turmas/",criata,name="aluno_turma"),
    path("p/<str:pk>/turmas/",criatp,name="professor_turma"),
    path("a/<str:pk>/turmas/tcreate/",crt,name="aluno_cria_turma"),
    path("p/<str:pk>/turmas/tcreate/",crtp,name="professor_cria_turma"),
    path("a/<str:pk>/turmas/<str:l>/",turseeal,name="aluno_turma_ver"),
    path("p/<str:pk>/turmas/<str:l>/",turseepr,name="professor_turma_ver"),
    path("a/<str:pk>/meusalunos/<str:pl>/",alunoseealuno,name="aluno_turma_ver"),
    path("p/<str:pk>/meusalunos/<str:pl>/",prseealuno,name="professor_turma_ver"),]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
