# Generated by Django 3.0.8 on 2020-11-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='comunicados',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='directoria',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='professor',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='turma',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60, verbose_name='slug'),
        ),
    ]
