# Generated by Django 3.0.8 on 2020-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandela', '0002_auto_20201102_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='sala',
            field=models.PositiveIntegerField(default=1, verbose_name='sala'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='sala',
            field=models.PositiveIntegerField(default=1, verbose_name='sala'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('Diurno', 'Diurno'), ('Noturno', 'Noturno')], default='diurno', max_length=100, verbose_name='turno'),
            preserve_default=False,
        ),
    ]
