# Generated by Django 3.0.8 on 2020-11-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandela', '0003_auto_20201103_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='classes',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='classes'),
        ),
    ]
