# Generated by Django 3.0.8 on 2020-11-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandela', '0004_professor_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='visto_de',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversa',
            name='visto_para',
            field=models.BooleanField(default=False),
        ),
    ]
