# Generated by Django 3.0.8 on 2020-11-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandela', '0007_auto_20201103_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='password',
        ),
    ]
