# Generated by Django 3.0.8 on 2020-11-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandela', '0009_auto_20201104_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicados',
            options={'ordering': ['data_de_criacao']},
        ),
        migrations.AlterModelOptions(
            name='directoria',
            options={'ordering': ['data_de_criacao']},
        ),
        migrations.AlterModelOptions(
            name='imagens',
            options={'ordering': ['data_de_criacao']},
        ),
        migrations.AlterModelOptions(
            name='messagems',
            options={'ordering': ['data_de_criacao']},
        ),
        migrations.AlterModelOptions(
            name='trabalho',
            options={'ordering': ['data_de_criacao']},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['data_de_criacao']},
        ),
    ]
